services:
  mongodb:
    image: mongo:7.0
    container_name: game-server-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=game-server
    volumes:
      - mongo-game-data:/data/db

volumes:
  mongo-game-data:
