services:
  mongodb:
    image: mongo:7.0
    container_name: task-api-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=task-api
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
